[package]
name = "AdventOfRust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "day1"
path = "src/day1/calories.rs"

[[bin]]
name = "day2"
path = "src/day2/rock_paper_scissors.rs"

[dependencies]
